// Shared types across web + scrapers consumers.
// db.types.ts is auto-generated by `supabase gen types` — do not edit by hand.

export type RiskLevel = "BAJO" | "MEDIO" | "ALTO" | "CRITICO";

export type EntityType =
  | "company"
  | "public_entity"
  | "person"
  | "political_org"
  | "contract"
  | "sancion"
  | "informe"
  | "aporte"
  | "dji"
  | "norma";

export type RelType =
  | "GANO_CONTRATO"
  | "POSTULO_EN"
  | "COMPRO_A"
  | "MIEMBRO_COMITE"
  | "FUNCIONARIO_EN"
  | "REPRESENTANTE_DE"
  | "FAMILIAR_DE"
  | "APORTO_A"
  | "CANDIDATO_EN"
  | "MISMO_DOMICILIO"
  | "MISMO_REPR_LEGAL"
  | "TIENE_SANCION"
  | "MENCIONADO_EN"
  | "VINCULO_DJI"
  | "GOVERNS"
  | "GENERATES_CASE"
  | "JUSTIFIES";

export type FlagId =
  | "unico_postor"
  | "contratacion_directa"
  | "concentracion_gasto"
  | "proveedor_sancionado"
  | "relacion_recurrente"
  | "plazo_corto"
  | "proceso_reiniciado"
  | "delta_monto"
  | "monto_atipico"
  | "sin_planeacion"
  | "no_habido"
  | "empresa_nueva"
  | "domicilio_compartido"
  | "representante_multi_empresa"
  | "conexion_politica_funcionario"
  | "conexion_politica_comite"
  | "conflicto_dji"
  | "familiar_proveedor";

export const RISK_THRESHOLDS = {
  BAJO: 0.0,
  MEDIO: 0.3,
  ALTO: 0.5,
  CRITICO: 0.7,
} as const;

export function nivelRiesgo(score: number): RiskLevel {
  if (score < RISK_THRESHOLDS.MEDIO) return "BAJO";
  if (score < RISK_THRESHOLDS.ALTO) return "MEDIO";
  if (score < RISK_THRESHOLDS.CRITICO) return "ALTO";
  return "CRITICO";
}
